/*
 * This source file was generated by the Gradle 'init' task
 */

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        assertNotNull(new App(), "app should build sucessfully!!");
    }
}
