version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/cpp"
      - "/cpp-low-level"
      - "/go"
      - "/javascript"
      - "/lua"
      - "/python"
      - "/ruby"
      - "/rust"
      - "/typescript"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dependabot"
    pull-request-branch-name:
      separator: "/"
