name: Build
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template:
          - cpp
          - cpp-low-level
          - go
          - java
          - javascript
          - lua
          - python
          - ruby
          - rust
          - typescript
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: current

      - name: Install Cartesi CLI
        run: npm install -g @cartesi/cli@2.0.0-alpha.34

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Check system requirements
        run: cartesi doctor

      - name: Build ${{ matrix.template }}
        run: cartesi build --debug
        working-directory: ${{ matrix.template }}

      - name: Print cartesi-machine hash
        run: cartesi hash
        working-directory: ${{ matrix.template }}

      - name: Upload root.ext2 artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.template }}-rootfs
          path: |
            ${{ matrix.template }}/.cartesi/root.ext2
            ${{ matrix.template }}/.cartesi/root.tar
