name: Build
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template:
          - cpp
          - cpp-low-level
          - go
          - java
          - javascript
          - lua
          - python
          - ruby
          - rust
          - typescript
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Cartesi SDK
        uses: cartesi/setup-action@2a783a3da2c5ada23c77f86262cf41caee1c88eb # v1.1.1
        with:
          cli-version: 2.0.0-alpha.34
          machine-version: 0.21.0

      - name: Check system requirements
        run: cartesi doctor

      - name: Build ${{ matrix.template }}
        run: cartesi build --verbose
        working-directory: ${{ matrix.template }}

      - name: Print cartesi-machine hash
        run: cartesi hash
        working-directory: ${{ matrix.template }}

      - name: Upload root.ext2 artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.template }}-rootfs
          path: |
            ${{ matrix.template }}/.cartesi/root.ext2
            ${{ matrix.template }}/.cartesi/root.tar
